## Non-candidate clean up

In [1]:
import pandas as pd

In [10]:
master = pd.read_csv("./person_2022_cd101222_v3.csv")

In [11]:
master.head()

,wmpid,full_name,name_fec,first_name,last_name,gender_wmp,fecid_2020,fecid_2022a,fecid_2022b,fecid_2022old,...,supcourt_2022,supcourt_former,currsen_2022,prompol,latino_wmp,latino_crp,race_wmp,race_crp1,race_crp2,race_crpmena
0,WMPID1,Mike Pence,"PENCE, MIKE",Mike,Pence,M,NaN,NaN,NaN,NaN,...,0,0.0,0,1,NaN,NaN,NaN,NaN,NaN,NaN
1,WMPID10,John Roberts,"ROBERTS, JOHN",John,Roberts,M,NaN,NaN,NaN,NaN,...,1,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,WMPID100,Rebecca Keltie,"KELTIE, REBECCA",Rebecca,Keltie,F,H0CO05152,H0CO05152,NaN,NaN,...,0,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,WMPID1000,Josh Gottheimer,"GOTTHEIMER, JOSH",Josh,Gottheimer,M,H6NJ05171,H6NJ05171,NaN,NaN,...,0,0.0,0,0,0.0,N,White,W,NaN,N
4,WMPID1001,Bill Pascrell Jr.,"PASCRELL, WILLIAM J. HON. JR.",Bill Jr,Pascrell,M,H6NJ08118,H6NJ08118,NaN,NaN,...,0,0.0,0,0,0.0,N,White,W,NaN,N

In [14]:
master.columns

Index(['wmpid', 'full_name', 'name_fec', 'first_name', 'last_name',
       'gender_wmp', 'fecid_2020', 'fecid_2022a', 'fecid_2022b',
       'fecid_2022old', 'fecid_changed', 'crp_candidate_id', 'face_url',
       'dateadded_person', 'notes_person', 'wmp_notes', 'genelect_cd_2022',
       'supcourt_2022', 'supcourt_former', 'currsen_2022', 'prompol',
       'latino_wmp', 'latino_crp', 'race_wmp', 'race_crp1', 'race_crp2',
       'race_crpmena'],
      dtype='object')

In [12]:
master['currsen_2022'].value_counts()

0    5065
1     100
Name: currsen_2022, dtype: int64

In [18]:
master.loc[(master['currsen_2022']==1)]

,wmpid,full_name,name_fec,first_name,last_name,gender_wmp,fecid_2020,fecid_2022a,fecid_2022b,fecid_2022old,...,supcourt_2022,supcourt_former,currsen_2022,prompol,latino_wmp,latino_crp,race_wmp,race_crp1,race_crp2,race_crpmena
330,WMPID1296,Tommy Tuberville,"TUBERVILLE, TOMMY",Tommy,Tuberville,M,S0AL00230,NaN,NaN,NaN,...,0,0.0,1,0,NaN,NaN,NaN,NaN,NaN,NaN
333,WMPID1299,John Boozman,"BOOZMAN, SEN. JOHN",John,Boozman,M,S0AR00150,S0AR00150,NaN,NaN,...,0,0.0,1,0,NaN,NaN,White,W,NaN,NaN
338,WMPID1302,Mark Kelly,"KELLY, MARK",Kelly,Mark,M,S0AZ00350,S0AZ00350,NaN,NaN,...,0,0.0,1,0,0.0,N,White,W,NaN,N
340,WMPID1304,Dianne Feinstein,"FEINSTEIN, DIANNE",Dianne,Feinstein,F,S0CA00199,NaN,NaN,NaN,...,0,0.0,1,0,NaN,NaN,NaN,NaN,NaN,NaN
341,WMPID1305,Michael Bennet,"BENNET, MICHAEL F.",Michael,Bennet,M,S0CO00211,S0CO00211,NaN,NaN,...,0,0.0,1,0,0.0,N,White,W,NaN,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,WMPID1547,Charles Schumer,"SCHUMER, CHARLES E.",Charles,Schumer,M,S8NY00082,S8NY00082,NaN,NaN,...,0,0.0,1,0,NaN,NaN,White,W,NaN,NaN
610,WMPID1548,Jeff Merkley,"MERKLEY, JEFF",Jeff,Merkley,M,S8OR00207,NaN,NaN,NaN,...,0,0.0,1,0,NaN,NaN,NaN,NaN,NaN,NaN
611,WMPID1549,Marsha Blackburn,"BLACKBURN, MARSHA",Marsha,Blackburn,F,S8TN00337,NaN,NaN,NaN,...,0,0.0,1,0,NaN,NaN,NaN,NaN,NaN,NaN
613,WMPID1550,Mitt Romney,"ROMNEY, MITT",Mitt,Romney,M,S8UT00176,NaN,NaN,NaN,...,0,0.0,1,0,NaN,NaN,NaN,NaN,NaN,NaN
614,WMPID1551,Maria Cantwell,"CANTWELL, MARIA",Maria,Cantwell,F,S8WA00194,NaN,NaN,NaN,...,0,0.0,1,0,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
master.loc[(master['supcourt_2022']==1)]

,wmpid,full_name,name_fec,first_name,last_name,gender_wmp,fecid_2020,fecid_2022a,fecid_2022b,fecid_2022old,...,supcourt_2022,supcourt_former,currsen_2022,prompol,latino_wmp,latino_crp,race_wmp,race_crp1,race_crp2,race_crpmena
1,WMPID10,John Roberts,"ROBERTS, JOHN",John,Roberts,M,NaN,NaN,NaN,NaN,...,1,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
112,WMPID11,Clarence Thomas,"THOMAS, CLARENCE",Clarence,Thomas,M,NaN,NaN,NaN,NaN,...,1,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
334,WMPID13,Elena Kagan,"KAGAN, ELENA",Elena,Kagan,F,NaN,NaN,NaN,NaN,...,1,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
445,WMPID14,Sonia Sotomayor,"SOTOMAYOR, SONIA",Sonia,Sotomayor,F,NaN,NaN,NaN,NaN,...,1,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
556,WMPID15,Neil Gorsuch,"GORSUCH, NEIL",Neil,Gorsuch,M,NaN,NaN,NaN,NaN,...,1,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
667,WMPID16,Brett Kavanaugh,"KAVANAUGH, BRETT",Brett,Kavanaugh,M,NaN,NaN,NaN,NaN,...,1,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
778,WMPID17,Amy Barrett,"BARRETT, AMY",Amy,Barrett,F,NaN,NaN,NaN,NaN,...,1,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4629,WMPID5166,Ketanji Brown Jackson,"JACKSON, KETANJI BROWN",Ketanji Brown,Jackson,F,NaN,NaN,NaN,NaN,...,1,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5054,WMPID9,Samuel Alito,"ALITO, SAMUEL",Samuel,Alito,M,NaN,NaN,NaN,NaN,...,1,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
master.loc[(master['supcourt_former']==1)]

,wmpid,full_name,name_fec,first_name,last_name,gender_wmp,fecid_2020,fecid_2022a,fecid_2022b,fecid_2022old,...,supcourt_2022,supcourt_former,currsen_2022,prompol,latino_wmp,latino_crp,race_wmp,race_crp1,race_crp2,race_crpmena
223,WMPID12,Stephen Breyer,"BREYER, STEPHEN",Stephen,Breyer,M,NaN,NaN,NaN,NaN,...,0,1.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
889,WMPID18,Ruth Ginsburg,"GINSBURG, RUTH",Ruth,Ginsburg,F,NaN,NaN,NaN,NaN,...,0,1.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1000,WMPID19,Antonin Scalia,"SCALIA, ANTONIN",Antonin,Scalia,M,NaN,NaN,NaN,NaN,...,0,1.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN